//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookImplement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CookImplement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _00_P {
            get {
                object obj = ResourceManager.GetObject("_00_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _01_F {
            get {
                object obj = ResourceManager.GetObject("_01_F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _02_E {
            get {
                object obj = ResourceManager.GetObject("_02_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _03_D {
            get {
                object obj = ResourceManager.GetObject("_03_D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _04_C {
            get {
                object obj = ResourceManager.GetObject("_04_C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _05_B {
            get {
                object obj = ResourceManager.GetObject("_05_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _06_A {
            get {
                object obj = ResourceManager.GetObject("_06_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _07_9 {
            get {
                object obj = ResourceManager.GetObject("_07_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _08_8 {
            get {
                object obj = ResourceManager.GetObject("_08_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _09_7 {
            get {
                object obj = ResourceManager.GetObject("_09_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _10_6 {
            get {
                object obj = ResourceManager.GetObject("_10_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _11_5 {
            get {
                object obj = ResourceManager.GetObject("_11_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _12_4 {
            get {
                object obj = ResourceManager.GetObject("_12_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _13_3 {
            get {
                object obj = ResourceManager.GetObject("_13_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _14_2 {
            get {
                object obj = ResourceManager.GetObject("_14_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _15_1 {
            get {
                object obj = ResourceManager.GetObject("_15_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button_cancel {
            get {
                object obj = ResourceManager.GetObject("button_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button_ok {
            get {
                object obj = ResourceManager.GetObject("button_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap critical {
            get {
                object obj = ResourceManager.GetObject("critical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 체력.
        /// </summary>
        public static string Effect1 {
            get {
                return ResourceManager.GetString("Effect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다이어트 효과.
        /// </summary>
        public static string Effect10 {
            get {
                return ResourceManager.GetString("Effect10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 지력.
        /// </summary>
        public static string Effect2 {
            get {
                return ResourceManager.GetString("Effect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 솜씨.
        /// </summary>
        public static string Effect3 {
            get {
                return ResourceManager.GetString("Effect3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 의지.
        /// </summary>
        public static string Effect4 {
            get {
                return ResourceManager.GetString("Effect4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 행운.
        /// </summary>
        public static string Effect5 {
            get {
                return ResourceManager.GetString("Effect5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최대생명력.
        /// </summary>
        public static string Effect6 {
            get {
                return ResourceManager.GetString("Effect6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최대마나.
        /// </summary>
        public static string Effect7 {
            get {
                return ResourceManager.GetString("Effect7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최대스태미너.
        /// </summary>
        public static string Effect8 {
            get {
                return ResourceManager.GetString("Effect8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스태미너 회복도.
        /// </summary>
        public static string Effect9 {
            get {
                return ResourceManager.GetString("Effect9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계속 진행하려면 아무 키나 누르세요..
        /// </summary>
        public static string MsgContinue {
            get {
                return ResourceManager.GetString("MsgContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 복사 되었습니다..
        /// </summary>
        public static string MsgCopied {
            get {
                return ResourceManager.GetString("MsgCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 입력한 데이터의 형식이 잘못 되었습니다..
        /// </summary>
        public static string MsgDataInvalid {
            get {
                return ResourceManager.GetString("MsgDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 재료 입수 방법을 입력하세요..
        /// </summary>
        public static string MsgInsertStuffHowToGet {
            get {
                return ResourceManager.GetString("MsgInsertStuffHowToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 재료 이름을 입력하세요..
        /// </summary>
        public static string MsgInsertStuffName {
            get {
                return ResourceManager.GetString("MsgInsertStuffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 재료 가격을 입력하세요..
        /// </summary>
        public static string MsgInsertStuffPrice {
            get {
                return ResourceManager.GetString("MsgInsertStuffPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 케이틴 = 0, 글리니스 = 1, 세나 = 2, 글루아스 = 3, 리리스 = 4,
        ///에피 = 5, 제니퍼 = 6, 루와이 = 7, 피에릭 = 8, 글라니테스 = 9,
        ///고든 = 10, 프레이저 = 11, 반스트 = 12, 채집 = 13, 요리 = 14, 
        ///루카스 = 15, 카독 = 16.
        /// </summary>
        public static string MsgLegend {
            get {
                return ResourceManager.GetString("MsgLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 줄리앙 닝.
        /// </summary>
        public static string Rank1 {
            get {
                return ResourceManager.GetString("Rank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 수족관.
        /// </summary>
        public static string Rank2 {
            get {
                return ResourceManager.GetString("Rank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발효.
        /// </summary>
        public static string Rank3 {
            get {
                return ResourceManager.GetString("Rank3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 피자 만들기.
        /// </summary>
        public static string Rank4 {
            get {
                return ResourceManager.GetString("Rank4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 김이 나는.
        /// </summary>
        public static string Rank5 {
            get {
                return ResourceManager.GetString("Rank5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파이.
        /// </summary>
        public static string Rank6 {
            get {
                return ResourceManager.GetString("Rank6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 잼.
        /// </summary>
        public static string Rank7 {
            get {
                return ResourceManager.GetString("Rank7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파스타.
        /// </summary>
        public static string Rank8 {
            get {
                return ResourceManager.GetString("Rank8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 볶기.
        /// </summary>
        public static string Rank9 {
            get {
                return ResourceManager.GetString("Rank9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 튀기기.
        /// </summary>
        public static string RankA {
            get {
                return ResourceManager.GetString("RankA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 면.
        /// </summary>
        public static string RankB {
            get {
                return ResourceManager.GetString("RankB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 끓이기.
        /// </summary>
        public static string RankC {
            get {
                return ResourceManager.GetString("RankC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 반죽.
        /// </summary>
        public static string RankD {
            get {
                return ResourceManager.GetString("RankD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삶기.
        /// </summary>
        public static string RankE {
            get {
                return ResourceManager.GetString("RankE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 굽기.
        /// </summary>
        public static string RankF {
            get {
                return ResourceManager.GetString("RankF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 혼합.
        /// </summary>
        public static string RankP {
            get {
                return ResourceManager.GetString("RankP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 케이틴.
        /// </summary>
        public static string Seller00 {
            get {
                return ResourceManager.GetString("Seller00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글리니스.
        /// </summary>
        public static string Seller01 {
            get {
                return ResourceManager.GetString("Seller01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 세나.
        /// </summary>
        public static string Seller02 {
            get {
                return ResourceManager.GetString("Seller02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글루아스.
        /// </summary>
        public static string Seller03 {
            get {
                return ResourceManager.GetString("Seller03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리리스.
        /// </summary>
        public static string Seller04 {
            get {
                return ResourceManager.GetString("Seller04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 에피.
        /// </summary>
        public static string Seller05 {
            get {
                return ResourceManager.GetString("Seller05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제니퍼.
        /// </summary>
        public static string Seller06 {
            get {
                return ResourceManager.GetString("Seller06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 루와이.
        /// </summary>
        public static string Seller07 {
            get {
                return ResourceManager.GetString("Seller07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 피에릭.
        /// </summary>
        public static string Seller08 {
            get {
                return ResourceManager.GetString("Seller08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글라니테스.
        /// </summary>
        public static string Seller09 {
            get {
                return ResourceManager.GetString("Seller09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 고든.
        /// </summary>
        public static string Seller10 {
            get {
                return ResourceManager.GetString("Seller10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프레이저.
        /// </summary>
        public static string Seller11 {
            get {
                return ResourceManager.GetString("Seller11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 반스트.
        /// </summary>
        public static string Seller12 {
            get {
                return ResourceManager.GetString("Seller12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 채집.
        /// </summary>
        public static string Seller13 {
            get {
                return ResourceManager.GetString("Seller13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 요리.
        /// </summary>
        public static string Seller14 {
            get {
                return ResourceManager.GetString("Seller14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 루카스.
        /// </summary>
        public static string Seller15 {
            get {
                return ResourceManager.GetString("Seller15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카독.
        /// </summary>
        public static string Seller16 {
            get {
                return ResourceManager.GetString("Seller16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아닉.
        /// </summary>
        public static string Seller17 {
            get {
                return ResourceManager.GetString("Seller17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 바날렌.
        /// </summary>
        public static string Seller18 {
            get {
                return ResourceManager.GetString("Seller18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배리.
        /// </summary>
        public static string Seller19 {
            get {
                return ResourceManager.GetString("Seller19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알림.
        /// </summary>
        public static string StrInfo {
            get {
                return ResourceManager.GetString("StrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 없음.
        /// </summary>
        public static string StrNothing {
            get {
                return ResourceManager.GetString("StrNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 요리재료.
        /// </summary>
        public static string StrStuff {
            get {
                return ResourceManager.GetString("StrStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
